// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	explore "backend/explore"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExploreServiceServer is an autogenerated mock type for the ExploreServiceServer type
type ExploreServiceServer struct {
	mock.Mock
}

// CountLikedYou provides a mock function with given fields: _a0, _a1
func (_m *ExploreServiceServer) CountLikedYou(_a0 context.Context, _a1 *explore.CountLikedYouRequest) (*explore.CountLikedYouResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CountLikedYou")
	}

	var r0 *explore.CountLikedYouResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *explore.CountLikedYouRequest) (*explore.CountLikedYouResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *explore.CountLikedYouRequest) *explore.CountLikedYouResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*explore.CountLikedYouResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *explore.CountLikedYouRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLikedYou provides a mock function with given fields: _a0, _a1
func (_m *ExploreServiceServer) ListLikedYou(_a0 context.Context, _a1 *explore.ListLikedYouRequest) (*explore.ListLikedYouResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListLikedYou")
	}

	var r0 *explore.ListLikedYouResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *explore.ListLikedYouRequest) (*explore.ListLikedYouResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *explore.ListLikedYouRequest) *explore.ListLikedYouResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*explore.ListLikedYouResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *explore.ListLikedYouRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNewLikedYou provides a mock function with given fields: _a0, _a1
func (_m *ExploreServiceServer) ListNewLikedYou(_a0 context.Context, _a1 *explore.ListLikedYouRequest) (*explore.ListLikedYouResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListNewLikedYou")
	}

	var r0 *explore.ListLikedYouResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *explore.ListLikedYouRequest) (*explore.ListLikedYouResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *explore.ListLikedYouRequest) *explore.ListLikedYouResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*explore.ListLikedYouResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *explore.ListLikedYouRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutDecision provides a mock function with given fields: _a0, _a1
func (_m *ExploreServiceServer) PutDecision(_a0 context.Context, _a1 *explore.PutDecisionRequest) (*explore.PutDecisionResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PutDecision")
	}

	var r0 *explore.PutDecisionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *explore.PutDecisionRequest) (*explore.PutDecisionResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *explore.PutDecisionRequest) *explore.PutDecisionResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*explore.PutDecisionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *explore.PutDecisionRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedExploreServiceServer provides a mock function with given fields:
func (_m *ExploreServiceServer) mustEmbedUnimplementedExploreServiceServer() {
	_m.Called()
}

// NewExploreServiceServer creates a new instance of ExploreServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExploreServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExploreServiceServer {
	mock := &ExploreServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
