// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeExploreServiceServer is an autogenerated mock type for the UnsafeExploreServiceServer type
type UnsafeExploreServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedExploreServiceServer provides a mock function with given fields:
func (_m *UnsafeExploreServiceServer) mustEmbedUnimplementedExploreServiceServer() {
	_m.Called()
}

// NewUnsafeExploreServiceServer creates a new instance of UnsafeExploreServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeExploreServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeExploreServiceServer {
	mock := &UnsafeExploreServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
